[package]
name = "theode"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
pbr = "1.1.1"
serde = { version = "1.0.213", features = ["derive"] }

[build-dependencies]
cc = "1.1.34"
